CC := gcc
CFLAGS := -Wall -Wextra -fpic
PROGRAMS := Sample1 \
	Sample2 \
	Sample3 \
	Sample4 \
	Sample5 \
	Sample6 \
	Sample7 \
	Sample8 \
	Sample9 \
	Sample10 \
	Sample11 \
	Sample12 \
	Sample13 \

all: $(PROGRAMS)

Sample13: Sample13.o myfunc.o

clean:
	$(RM) $(PROGRAMS) *.o
