CC := g++
CPPFLAGS := -g -Wall -Wextra -fPIC
PROGRAM := list4_1 \
	list4_2 \
	list4_3 \
	list4_4 \
	list4_5 \
	list4_6 \
	list4_7 \
	list4_8 \
	list4_9 \
	list4_10 \
	list4_11 \
	list4_12 \

all:$(PROGRAM)
	
clean:
	rm -f $(PROGRAM)
