CC := gcc
CFLAGS := -Wall -Wextra -fpic
PROGRAMS := Sample1 \
	Sample2 \
	Sample3 \
	Sample4 \
	Sample5 \
	Sample6 \
	Sample7 \
	Sample8 \
	Sample9 \
	Sample10 \
	Sample11 \
	Sample12 \
	Sample13 \
	Sample14 \
	Sample15 \
	Sample16 \
	Sample17 \
	Sample18 \

all: $(PROGRAMS)

clean:
	$(RM) $(PROGRAMS)
